apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # Nombre de la aplicación en la interfaz de ArgoCD
  name: tutorias-universitarias-stack
  # El namespace donde reside ArgoCD (generalmente argocd)
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ElianaJulca/Ejercicio.git
    targetRevision: HEAD
    # ESTA ES LA LÍNEA CRÍTICA A CORREGIR:
    path: Documents/Final-Tutorias-Universitarias-2-main/tutorias-stack
    # Si la estructura fuera diferente, usarías la ruta exacta:
    # path: Final-Tutorias-Universitarias-2-main/tutorias-stack 
  destination:
    server: https://kubernetes.default.svc
    # El Namespace donde se desplegarán todos los microservicios
    namespace: tutorias
  # --- POLÍTICA GITOPS ---
  syncPolicy:
    automated:
      # ArgoCD aplicará los cambios automáticamente cuando detecte una diferencia en Git
      prune: true
      selfHeal: true # Si alguien borra algo, ArgoCD lo recrea inmediatamente (Resurrección)
    syncOptions:
    - CreateNamespace=true # Permite que ArgoCD cree el namespace 'tutorias'
    - ServerSideApply=true # Recomendado para manejar charts complejos