# kubernetes-manifests/secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: tutorias-secrets # Nombre centralizado para todos los secrets
type: Opaque # Tipo estándar para datos definidos por el usuario
stringData:
  # --- 1. Credencial JWT para firmar y validar tokens ---
  JWT_SECRET: "ESTE_ES_UN_SECRETO_PARA_DESARROLLO_NO_USAR_EN_PROD"
  
  # --- 2. Credenciales de RabbitMQ ---
  RABBITMQ_USER: "user"
  RABBITMQ_PASSWORD: "password"
  
  # --- 3. Credenciales para db-tutorias (usadas por ms-tutorias) ---
  DB_USER_TUTORIAS: "user_tutorias"
  DB_PASSWORD_TUTORIAS: "password_tutorias"

  # --- 4. Credenciales para db-usuarios (usadas por ms-usuarios) ---
  DB_USER_USUARIOS: "user_usuarios"
  DB_PASSWORD_USUARIOS: "password_usuarios"
  
  # --- 5. Credenciales para db-agenda (usadas por ms-agenda) ---
  DB_USER_AGENDA: "user_agenda"
  DB_PASSWORD_AGENDA: "password_agenda"